"""
Euler Project - Problem Two

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

https://projecteuler.net/problem=2

"""

def main():
    a,b = 1,2
    limit = 4000000
    fibList = []
    sumList = []
    while a < limit: 
        fibList.append(a)
        a,b = b, a+b

    for i in fibList:
        if i % 2 == 0:
            sumList.append(i)
        else: 
            pass
    
    print(sum(sumList))

if __name__ == '__main__':
    main()


"""
The Result is: 4613732
"""